create table if not exists dv_action_templates (
  id text primary key,
  name text not null,
  category text not null check (category in ('skincare', 'workout', 'meal_prep', 'recipe')),
  schema_version int not null default 1,
  template_version int not null default 1,
  status text not null default 'draft' check (status in ('draft', 'submitted', 'approved', 'rejected')),
  is_public boolean not null default false,
  is_official boolean not null default false,
  set_key text,
  steps_json jsonb not null,
  metadata_json jsonb not null default '{}'::jsonb,
  created_by text not null,
  reviewed_by text,
  review_notes text,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists dv_action_templates_category_status_updated_idx
  on dv_action_templates (category, status, updated_at desc);
create index if not exists dv_action_templates_created_by_updated_idx
  on dv_action_templates (created_by, updated_at desc);
create index if not exists dv_action_templates_set_key_idx
  on dv_action_templates (set_key);

insert into dv_action_templates (
  id, name, category, schema_version, template_version, status, is_public, is_official, set_key, steps_json, metadata_json, created_by
)
values
  (
    'default_set_beginner_skincare',
    'Beginner AM/PM Skincare',
    'skincare',
    1,
    1,
    'approved',
    true,
    true,
    'default_set_beginner',
    jsonb_build_array(
      jsonb_build_object('id','step-1','title','Cleanser','iconCodePoint',58823,'order',0),
      jsonb_build_object('id','step-2','title','Toner','iconCodePoint',58823,'order',1),
      jsonb_build_object('id','step-3','title','Serum','iconCodePoint',58823,'order',2),
      jsonb_build_object('id','step-4','title','Moisturizer','iconCodePoint',58823,'order',3),
      jsonb_build_object('id','step-5','title','Sunscreen','iconCodePoint',58823,'order',4)
    ),
    '{}'::jsonb,
    'system'
  ),
  (
    'default_set_structured_skincare',
    'Structured Concern-Based Skincare',
    'skincare',
    1,
    1,
    'approved',
    true,
    true,
    'default_set_structured',
    jsonb_build_array(
      jsonb_build_object('id','step-1','title','Cleanser','iconCodePoint',58823,'order',0),
      jsonb_build_object('id','step-2','title','Exfoliate (optional)','iconCodePoint',58823,'order',1),
      jsonb_build_object('id','step-3','title','Treatment serum','iconCodePoint',58823,'order',2),
      jsonb_build_object('id','step-4','title','Moisturizer','iconCodePoint',58823,'order',3),
      jsonb_build_object('id','step-5','title','SPF','iconCodePoint',58823,'order',4)
    ),
    '{}'::jsonb,
    'system'
  ),
  -- ── Workout: Beginner ─────────────────────────────────────────────────────
  -- Source: https://www.muscleandstrength.com/workouts/start-from-scratch-beginner-workout
  (
    'default_set_beginner_workout',
    'Start from Scratch – 6 Week Full Body',
    'workout',
    2,
    1,
    'approved',
    true,
    true,
    'default_set_beginner',
    jsonb_build_array(
      -- Workout A (Mon & Thu) — Upper Body Focus
      jsonb_build_object('id','w-a1','title','Barbell Bench Press','iconCodePoint',58728,'order',0,
        'plannerDay','Workout A – Mon & Thu','stepLabel','2 × 8–10','productType','Chest',
        'productName','Barbell','notes','Warm-up set required. 2 sec up, 2 sec down.'),
      jsonb_build_object('id','w-a2','title','Incline Dumbbell Press','iconCodePoint',58728,'order',1,
        'plannerDay','Workout A – Mon & Thu','stepLabel','2 × 10','productType','Chest',
        'productName','Dumbbell','notes',''),
      jsonb_build_object('id','w-a3','title','Bent-Over Barbell Row','iconCodePoint',58728,'order',2,
        'plannerDay','Workout A – Mon & Thu','stepLabel','2 × 8–10','productType','Back',
        'productName','Barbell','notes','Keep back flat and neutral throughout'),
      jsonb_build_object('id','w-a4','title','Lat Pulldown','iconCodePoint',58728,'order',3,
        'plannerDay','Workout A – Mon & Thu','stepLabel','2 × 10','productType','Back',
        'productName','Cable Machine','notes',''),
      jsonb_build_object('id','w-a5','title','Barbell Overhead Press','iconCodePoint',58728,'order',4,
        'plannerDay','Workout A – Mon & Thu','stepLabel','2 × 8–10','productType','Shoulders',
        'productName','Barbell','notes','Press in a straight line overhead'),
      jsonb_build_object('id','w-a6','title','Dumbbell Curl','iconCodePoint',58728,'order',5,
        'plannerDay','Workout A – Mon & Thu','stepLabel','2 × 10','productType','Biceps',
        'productName','Dumbbell','notes',''),
      jsonb_build_object('id','w-a7','title','Tricep Rope Pushdown','iconCodePoint',58728,'order',6,
        'plannerDay','Workout A – Mon & Thu','stepLabel','2 × 10','productType','Triceps',
        'productName','Cable Machine','notes',''),
      -- Workout B (Tue & Fri) — Lower Body & Core
      jsonb_build_object('id','w-b1','title','Barbell Back Squat','iconCodePoint',58728,'order',7,
        'plannerDay','Workout B – Tue & Fri','stepLabel','2 × 10–12','productType','Legs',
        'productName','Barbell','notes','Warm-up set required. Sit back, keep chest up.'),
      jsonb_build_object('id','w-b2','title','Romanian Deadlift','iconCodePoint',58728,'order',8,
        'plannerDay','Workout B – Tue & Fri','stepLabel','2 × 10–12','productType','Hamstrings',
        'productName','Barbell','notes','Feel the stretch at the bottom'),
      jsonb_build_object('id','w-b3','title','Leg Press','iconCodePoint',58728,'order',9,
        'plannerDay','Workout B – Tue & Fri','stepLabel','2 × 12','productType','Legs',
        'productName','Machine','notes',''),
      jsonb_build_object('id','w-b4','title','Leg Curl','iconCodePoint',58728,'order',10,
        'plannerDay','Workout B – Tue & Fri','stepLabel','2 × 12','productType','Hamstrings',
        'productName','Machine','notes',''),
      jsonb_build_object('id','w-b5','title','Standing Calf Raise','iconCodePoint',58728,'order',11,
        'plannerDay','Workout B – Tue & Fri','stepLabel','2 × 15','productType','Calves',
        'productName','Machine','notes',''),
      jsonb_build_object('id','w-b6','title','Plank','iconCodePoint',58728,'order',12,
        'plannerDay','Workout B – Tue & Fri','stepLabel','2 × 30 sec','productType','Core',
        'productName','Bodyweight','notes',''),
      jsonb_build_object('id','w-b7','title','Crunches','iconCodePoint',58728,'order',13,
        'plannerDay','Workout B – Tue & Fri','stepLabel','2 × 15–20','productType','Core',
        'productName','Bodyweight','notes','')
    ),
    jsonb_build_object(
      'goal','Build Muscle & Strength',
      'level','Beginner',
      'durationWeeks',6,
      'daysPerWeek',4,
      'schedule','Mon / Tue / Thu / Fri',
      'split','Full Body – Workout A + B alternating',
      'timePerSession','45–60 min',
      'equipment',jsonb_build_array('Barbell','Dumbbell','Cable Machine','Bench','Machine'),
      'source','https://www.muscleandstrength.com/workouts/start-from-scratch-beginner-workout',
      'note','Two alternating full-body workouts. Use a 2-second tempo (up and down) on all reps. Warm-up sets required on marked exercises.'
    ),
    'system'
  ),
  -- ── Workout: Intermediate ─────────────────────────────────────────────────
  -- Source: https://www.muscleandstrength.com/workouts/8-week-hypertrophy-workout
  (
    'default_set_structured_workout',
    '8-Week Mass Building Hypertrophy',
    'workout',
    2,
    1,
    'approved',
    true,
    true,
    'default_set_structured',
    jsonb_build_array(
      -- Workout 1: Chest & Side Delts (Monday)
      jsonb_build_object('id','h-1a','title','Incline Barbell Bench Press','iconCodePoint',58728,'order',0,
        'plannerDay','Workout 1 – Mon (Chest & Side Delts)','stepLabel','3 × 12, 10, 12*','productType','Chest',
        'productName','Barbell','notes','*Rest-Pause Set on final set'),
      jsonb_build_object('id','h-1b','title','Flat Dumbbell Bench Press','iconCodePoint',58728,'order',1,
        'plannerDay','Workout 1 – Mon (Chest & Side Delts)','stepLabel','3 × 12, 10, 15+','productType','Chest',
        'productName','Dumbbell','notes','+Drop Set on final set'),
      jsonb_build_object('id','h-1c','title','Cable Crossover','iconCodePoint',58728,'order',2,
        'plannerDay','Workout 1 – Mon (Chest & Side Delts)','stepLabel','3 × 12, 12, 12^','productType','Chest',
        'productName','Cable Machine','notes','^3–5 sec negatives on final set'),
      jsonb_build_object('id','h-1d','title','Seated Lateral Raise','iconCodePoint',58728,'order',3,
        'plannerDay','Workout 1 – Mon (Chest & Side Delts)','stepLabel','3 × 12','productType','Side Delts',
        'productName','Dumbbell','notes',''),
      jsonb_build_object('id','h-1e','title','Cable Lateral Raise','iconCodePoint',58728,'order',4,
        'plannerDay','Workout 1 – Mon (Chest & Side Delts)','stepLabel','3 × 12','productType','Side Delts',
        'productName','Cable Machine','notes',''),
      -- Workout 2: Back & Rear Delts (Tuesday)
      jsonb_build_object('id','h-2a','title','Bent-Over Barbell Row','iconCodePoint',58728,'order',5,
        'plannerDay','Workout 2 – Tue (Back & Rear Delts)','stepLabel','3 × 12, 10, 12*','productType','Back',
        'productName','Barbell','notes','*Rest-Pause Set'),
      jsonb_build_object('id','h-2b','title','Dumbbell Pullover','iconCodePoint',58728,'order',6,
        'plannerDay','Workout 2 – Tue (Back & Rear Delts)','stepLabel','3 × 12, 10, 15+','productType','Back',
        'productName','Dumbbell','notes','+Drop Set'),
      jsonb_build_object('id','h-2c','title','Wide Grip Lat Pulldown','iconCodePoint',58728,'order',7,
        'plannerDay','Workout 2 – Tue (Back & Rear Delts)','stepLabel','3 × 12, 12, 12^','productType','Back',
        'productName','Cable Machine','notes','^3–5 sec negatives'),
      jsonb_build_object('id','h-2d','title','Dumbbell Rear Delt Fly','iconCodePoint',58728,'order',8,
        'plannerDay','Workout 2 – Tue (Back & Rear Delts)','stepLabel','3 × 12','productType','Rear Delts',
        'productName','Dumbbell','notes',''),
      jsonb_build_object('id','h-2e','title','Cable Face Pull','iconCodePoint',58728,'order',9,
        'plannerDay','Workout 2 – Tue (Back & Rear Delts)','stepLabel','3 × 12','productType','Rear Delts',
        'productName','Cable Machine','notes',''),
      jsonb_build_object('id','h-2f','title','Dumbbell Shrug','iconCodePoint',58728,'order',10,
        'plannerDay','Workout 2 – Tue (Back & Rear Delts)','stepLabel','3 × 12','productType','Traps',
        'productName','Dumbbell','notes',''),
      -- Workout 3: Arms & Abs (Thursday)
      jsonb_build_object('id','h-3a','title','Barbell Curl','iconCodePoint',58728,'order',11,
        'plannerDay','Workout 3 – Thu (Arms & Abs)','stepLabel','3 × 12, 10, 8*','productType','Biceps',
        'productName','Barbell','notes','*Rest-Pause Set'),
      jsonb_build_object('id','h-3b','title','Incline Dumbbell Curl','iconCodePoint',58728,'order',12,
        'plannerDay','Workout 3 – Thu (Arms & Abs)','stepLabel','3 × 12','productType','Biceps',
        'productName','Dumbbell','notes',''),
      jsonb_build_object('id','h-3c','title','Hammer Curl','iconCodePoint',58728,'order',13,
        'plannerDay','Workout 3 – Thu (Arms & Abs)','stepLabel','3 × 12, 12, 12+','productType','Biceps',
        'productName','Dumbbell','notes','+Drop Set on final set'),
      jsonb_build_object('id','h-3d','title','Tricep Rope Pushdown','iconCodePoint',58728,'order',14,
        'plannerDay','Workout 3 – Thu (Arms & Abs)','stepLabel','3 × 12, 10, 8*','productType','Triceps',
        'productName','Cable Machine','notes','*Rest-Pause Set'),
      jsonb_build_object('id','h-3e','title','Skull Crusher','iconCodePoint',58728,'order',15,
        'plannerDay','Workout 3 – Thu (Arms & Abs)','stepLabel','3 × 12, 12, 12^','productType','Triceps',
        'productName','Barbell','notes','^3–5 sec negatives'),
      jsonb_build_object('id','h-3f','title','Cable Crunch','iconCodePoint',58728,'order',16,
        'plannerDay','Workout 3 – Thu (Arms & Abs)','stepLabel','3 × 15','productType','Core',
        'productName','Cable Machine','notes',''),
      jsonb_build_object('id','h-3g','title','Hanging Leg Raise','iconCodePoint',58728,'order',17,
        'plannerDay','Workout 3 – Thu (Arms & Abs)','stepLabel','3 × 12','productType','Core',
        'productName','Bodyweight','notes',''),
      -- Workout 4: Legs (Friday)
      jsonb_build_object('id','h-4a','title','Barbell Back Squat','iconCodePoint',58728,'order',18,
        'plannerDay','Workout 4 – Fri (Legs)','stepLabel','3 × 12, 10, 8*','productType','Quads',
        'productName','Barbell','notes','*Rest-Pause Set. Explode up, control down.'),
      jsonb_build_object('id','h-4b','title','Leg Press','iconCodePoint',58728,'order',19,
        'plannerDay','Workout 4 – Fri (Legs)','stepLabel','3 × 12, 12, 15+','productType','Quads',
        'productName','Machine','notes','+Drop Set on final set'),
      jsonb_build_object('id','h-4c','title','Romanian Deadlift','iconCodePoint',58728,'order',20,
        'plannerDay','Workout 4 – Fri (Legs)','stepLabel','3 × 12, 10, 12^','productType','Hamstrings',
        'productName','Barbell','notes','^3–5 sec negatives. Feel the hamstring stretch.'),
      jsonb_build_object('id','h-4d','title','Leg Curl','iconCodePoint',58728,'order',21,
        'plannerDay','Workout 4 – Fri (Legs)','stepLabel','3 × 12','productType','Hamstrings',
        'productName','Machine','notes',''),
      jsonb_build_object('id','h-4e','title','Leg Extension','iconCodePoint',58728,'order',22,
        'plannerDay','Workout 4 – Fri (Legs)','stepLabel','3 × 12','productType','Quads',
        'productName','Machine','notes',''),
      jsonb_build_object('id','h-4f','title','Standing Calf Raise','iconCodePoint',58728,'order',23,
        'plannerDay','Workout 4 – Fri (Legs)','stepLabel','4 × 15','productType','Calves',
        'productName','Machine','notes','')
    ),
    jsonb_build_object(
      'goal','Build Muscle Mass',
      'level','Intermediate',
      'durationWeeks',8,
      'daysPerWeek',4,
      'schedule','Mon / Tue / Thu / Fri',
      'split','Chest+Delts / Back+Rear Delts / Arms+Abs / Legs',
      'timePerSession','60–75 min',
      'equipment',jsonb_build_array('Barbell','Dumbbell','Cable Machine','Machines'),
      'source','https://www.muscleandstrength.com/workouts/8-week-hypertrophy-workout',
      'note','Uses intensity techniques: * = Rest-Pause (rest 10–15 sec, push more reps), + = Drop Set (reduce weight, push to failure), ^ = 3–5 sec negatives.'
    ),
    'system'
  ),
  -- ── Workout: Advanced ─────────────────────────────────────────────────────
  -- Source: https://www.muscleandstrength.com/workouts/big-and-strong-advanced-program
  (
    'default_set_advanced_workout',
    'Big & Strong – 8 Week Advanced Strength',
    'workout',
    2,
    1,
    'approved',
    true,
    true,
    'default_set_advanced',
    jsonb_build_array(
      -- Day 1: Squat & Lower Body (Monday)
      jsonb_build_object('id','s-1a','title','Barbell Back Squat','iconCodePoint',58728,'order',0,
        'plannerDay','Day 1 – Mon (Squat & Lower Body)','stepLabel','5 × 5','productType','Legs',
        'productName','Barbell','notes','Work up to a heavy 5-rep set. Explosive power out of the hole.'),
      jsonb_build_object('id','s-1b','title','Front Squat','iconCodePoint',58728,'order',1,
        'plannerDay','Day 1 – Mon (Squat & Lower Body)','stepLabel','3 × 5','productType','Legs',
        'productName','Barbell','notes',''),
      jsonb_build_object('id','s-1c','title','Leg Press','iconCodePoint',58728,'order',2,
        'plannerDay','Day 1 – Mon (Squat & Lower Body)','stepLabel','3 × 8','productType','Legs',
        'productName','Machine','notes',''),
      jsonb_build_object('id','s-1d','title','Leg Extension','iconCodePoint',58728,'order',3,
        'plannerDay','Day 1 – Mon (Squat & Lower Body)','stepLabel','3 × 10','productType','Quads',
        'productName','Machine','notes',''),
      jsonb_build_object('id','s-1e','title','Leg Curl','iconCodePoint',58728,'order',4,
        'plannerDay','Day 1 – Mon (Squat & Lower Body)','stepLabel','3 × 10','productType','Hamstrings',
        'productName','Machine','notes',''),
      jsonb_build_object('id','s-1f','title','Standing Calf Raise','iconCodePoint',58728,'order',5,
        'plannerDay','Day 1 – Mon (Squat & Lower Body)','stepLabel','4 × 12','productType','Calves',
        'productName','Machine','notes',''),
      -- Day 2: Bench & Chest (Tuesday)
      jsonb_build_object('id','s-2a','title','Barbell Bench Press','iconCodePoint',58728,'order',6,
        'plannerDay','Day 2 – Tue (Bench & Chest)','stepLabel','5 × 5','productType','Chest',
        'productName','Barbell','notes','Work up to heavy 5. Drive legs into floor, stay tight.'),
      jsonb_build_object('id','s-2b','title','Incline Barbell Bench Press','iconCodePoint',58728,'order',7,
        'plannerDay','Day 2 – Tue (Bench & Chest)','stepLabel','3 × 6','productType','Chest',
        'productName','Barbell','notes',''),
      jsonb_build_object('id','s-2c','title','Dumbbell Flye','iconCodePoint',58728,'order',8,
        'plannerDay','Day 2 – Tue (Bench & Chest)','stepLabel','3 × 10','productType','Chest',
        'productName','Dumbbell','notes',''),
      jsonb_build_object('id','s-2d','title','Weighted Dip','iconCodePoint',58728,'order',9,
        'plannerDay','Day 2 – Tue (Bench & Chest)','stepLabel','3 × 8','productType','Triceps',
        'productName','Bodyweight','notes','Add weight via belt when 10+ reps become easy'),
      jsonb_build_object('id','s-2e','title','Skull Crusher','iconCodePoint',58728,'order',10,
        'plannerDay','Day 2 – Tue (Bench & Chest)','stepLabel','3 × 10','productType','Triceps',
        'productName','Barbell','notes',''),
      -- Day 3: Deadlift & Back (Wednesday)
      jsonb_build_object('id','s-3a','title','Conventional Deadlift','iconCodePoint',58728,'order',11,
        'plannerDay','Day 3 – Wed (Deadlift & Back)','stepLabel','5 × 3–5','productType','Back',
        'productName','Barbell','notes','Work up to a heavy top set. Reset between each rep.'),
      jsonb_build_object('id','s-3b','title','Barbell Row','iconCodePoint',58728,'order',12,
        'plannerDay','Day 3 – Wed (Deadlift & Back)','stepLabel','4 × 6','productType','Back',
        'productName','Barbell','notes',''),
      jsonb_build_object('id','s-3c','title','Wide-Grip Pull-Up','iconCodePoint',58728,'order',13,
        'plannerDay','Day 3 – Wed (Deadlift & Back)','stepLabel','3 × Max','productType','Back',
        'productName','Bodyweight','notes','Add weight if you can get 10+ reps easily'),
      jsonb_build_object('id','s-3d','title','T-Bar Row','iconCodePoint',58728,'order',14,
        'plannerDay','Day 3 – Wed (Deadlift & Back)','stepLabel','3 × 8','productType','Back',
        'productName','Barbell','notes',''),
      jsonb_build_object('id','s-3e','title','Barbell Curl','iconCodePoint',58728,'order',15,
        'plannerDay','Day 3 – Wed (Deadlift & Back)','stepLabel','3 × 8','productType','Biceps',
        'productName','Barbell','notes',''),
      jsonb_build_object('id','s-3f','title','Cable Face Pull','iconCodePoint',58728,'order',16,
        'plannerDay','Day 3 – Wed (Deadlift & Back)','stepLabel','3 × 15','productType','Rear Delts',
        'productName','Cable Machine','notes','Great for shoulder health and posture'),
      -- Day 4: Overhead Press & Shoulders (Thursday)
      jsonb_build_object('id','s-4a','title','Barbell Overhead Press','iconCodePoint',58728,'order',17,
        'plannerDay','Day 4 – Thu (OHP & Shoulders)','stepLabel','5 × 5','productType','Shoulders',
        'productName','Barbell','notes','Standing. Press in a straight line overhead.'),
      jsonb_build_object('id','s-4b','title','Arnold Dumbbell Press','iconCodePoint',58728,'order',18,
        'plannerDay','Day 4 – Thu (OHP & Shoulders)','stepLabel','3 × 8','productType','Shoulders',
        'productName','Dumbbell','notes',''),
      jsonb_build_object('id','s-4c','title','Dumbbell Lateral Raise','iconCodePoint',58728,'order',19,
        'plannerDay','Day 4 – Thu (OHP & Shoulders)','stepLabel','3 × 12','productType','Side Delts',
        'productName','Dumbbell','notes',''),
      jsonb_build_object('id','s-4d','title','Rear Delt Fly','iconCodePoint',58728,'order',20,
        'plannerDay','Day 4 – Thu (OHP & Shoulders)','stepLabel','3 × 12','productType','Rear Delts',
        'productName','Dumbbell','notes',''),
      jsonb_build_object('id','s-4e','title','Barbell Shrug','iconCodePoint',58728,'order',21,
        'plannerDay','Day 4 – Thu (OHP & Shoulders)','stepLabel','3 × 10','productType','Traps',
        'productName','Barbell','notes',''),
      -- Day 5: Accessory & Hypertrophy (Friday)
      jsonb_build_object('id','s-5a','title','Dumbbell Lunge','iconCodePoint',58728,'order',22,
        'plannerDay','Day 5 – Fri (Accessory & Hypertrophy)','stepLabel','3 × 10 each','productType','Legs',
        'productName','Dumbbell','notes','Alternate legs'),
      jsonb_build_object('id','s-5b','title','Dumbbell Row','iconCodePoint',58728,'order',23,
        'plannerDay','Day 5 – Fri (Accessory & Hypertrophy)','stepLabel','3 × 10','productType','Back',
        'productName','Dumbbell','notes',''),
      jsonb_build_object('id','s-5c','title','Dumbbell Shoulder Press','iconCodePoint',58728,'order',24,
        'plannerDay','Day 5 – Fri (Accessory & Hypertrophy)','stepLabel','3 × 10','productType','Shoulders',
        'productName','Dumbbell','notes',''),
      jsonb_build_object('id','s-5d','title','Incline Dumbbell Curl','iconCodePoint',58728,'order',25,
        'plannerDay','Day 5 – Fri (Accessory & Hypertrophy)','stepLabel','3 × 12','productType','Biceps',
        'productName','Dumbbell','notes',''),
      jsonb_build_object('id','s-5e','title','Tricep Overhead Extension','iconCodePoint',58728,'order',26,
        'plannerDay','Day 5 – Fri (Accessory & Hypertrophy)','stepLabel','3 × 12','productType','Triceps',
        'productName','Dumbbell','notes',''),
      jsonb_build_object('id','s-5f','title','Hanging Leg Raise','iconCodePoint',58728,'order',27,
        'plannerDay','Day 5 – Fri (Accessory & Hypertrophy)','stepLabel','3 × 15','productType','Core',
        'productName','Bodyweight','notes',''),
      jsonb_build_object('id','s-5g','title','Cable Crunch','iconCodePoint',58728,'order',28,
        'plannerDay','Day 5 – Fri (Accessory & Hypertrophy)','stepLabel','3 × 15','productType','Core',
        'productName','Cable Machine','notes','')
    ),
    jsonb_build_object(
      'goal','Build Strength & Power',
      'level','Advanced',
      'durationWeeks',8,
      'daysPerWeek',5,
      'schedule','Mon / Tue / Wed / Thu / Fri',
      'split','Squat / Bench / Deadlift / OHP / Accessory',
      'timePerSession','60–90 min',
      'equipment',jsonb_build_array('Barbell','Dumbbell','Cable Machine','Power Rack','Machines'),
      'source','https://www.muscleandstrength.com/workouts/big-and-strong-advanced-program',
      'note','For lifters with 1+ year of experience. Focus on progressive overload on all main lifts. Rest 3–5 min between heavy compound sets.'
    ),
    'system'
  ),
  (
    'default_set_beginner_meal_prep',
    'Beginner Weekly Meal Prep',
    'meal_prep',
    1,
    1,
    'approved',
    true,
    true,
    'default_set_beginner',
    jsonb_build_array(
      jsonb_build_object('id','step-1','title','Pick 3 meals','iconCodePoint',58134,'order',0),
      jsonb_build_object('id','step-2','title','Prepare grocery list','iconCodePoint',58134,'order',1),
      jsonb_build_object('id','step-3','title','Batch cook','iconCodePoint',58134,'order',2),
      jsonb_build_object('id','step-4','title','Portion and store','iconCodePoint',58134,'order',3)
    ),
    '{}'::jsonb,
    'system'
  ),
  (
    'default_set_structured_meal_prep',
    'Structured Batch + Leftovers Plan',
    'meal_prep',
    1,
    1,
    'approved',
    true,
    true,
    'default_set_structured',
    jsonb_build_array(
      jsonb_build_object('id','step-1','title','Plan macros for week','iconCodePoint',58134,'order',0),
      jsonb_build_object('id','step-2','title','Shop by category','iconCodePoint',58134,'order',1),
      jsonb_build_object('id','step-3','title','Cook proteins in batches','iconCodePoint',58134,'order',2),
      jsonb_build_object('id','step-4','title','Prep carbs and vegetables','iconCodePoint',58134,'order',3),
      jsonb_build_object('id','step-5','title','Label and refrigerate','iconCodePoint',58134,'order',4)
    ),
    '{}'::jsonb,
    'system'
  ),
  (
    'default_set_beginner_recipe',
    'Beginner Recipe Workflow',
    'recipe',
    1,
    1,
    'approved',
    true,
    true,
    'default_set_beginner',
    jsonb_build_array(
      jsonb_build_object('id','step-1','title','List ingredients','iconCodePoint',58134,'order',0),
      jsonb_build_object('id','step-2','title','Prep ingredients','iconCodePoint',58134,'order',1),
      jsonb_build_object('id','step-3','title','Cook in sequence','iconCodePoint',58134,'order',2),
      jsonb_build_object('id','step-4','title','Taste and adjust','iconCodePoint',58134,'order',3)
    ),
    '{}'::jsonb,
    'system'
  ),
  (
    'default_set_structured_recipe',
    'Structured Method-Varied Recipe',
    'recipe',
    1,
    1,
    'approved',
    true,
    true,
    'default_set_structured',
    jsonb_build_array(
      jsonb_build_object('id','step-1','title','Mise en place','iconCodePoint',58134,'order',0),
      jsonb_build_object('id','step-2','title','Primary method (air fryer/steam/etc)','iconCodePoint',58134,'order',1),
      jsonb_build_object('id','step-3','title','Secondary finish method','iconCodePoint',58134,'order',2),
      jsonb_build_object('id','step-4','title','Plate and note tweaks','iconCodePoint',58134,'order',3)
    ),
    '{}'::jsonb,
    'system'
  )
on conflict (id) do update
set
  name = excluded.name,
  category = excluded.category,
  schema_version = excluded.schema_version,
  template_version = excluded.template_version,
  status = excluded.status,
  is_public = excluded.is_public,
  is_official = excluded.is_official,
  set_key = excluded.set_key,
  steps_json = excluded.steps_json,
  metadata_json = excluded.metadata_json,
  updated_at = now();

