// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxMb8VRtABCQZr5cHKzPPs6EFFhCmG8I0',
    appId: '1:612736301895:web:70986d26c495c49dac2a62',
    messagingSenderId: '612736301895',
    projectId: 'habitseeding-prod',
    authDomain: 'habitseeding-prod.firebaseapp.com',
    storageBucket: 'habitseeding-prod.firebasestorage.app',
    measurementId: 'G-R3DWZM8RLX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKhG2BAIy_5ZDmmYyR3Ir8WXCt4URJXIE',
    appId: '1:612736301895:android:54524ee804a74a4eac2a62',
    messagingSenderId: '612736301895',
    projectId: 'habitseeding-prod',
    storageBucket: 'habitseeding-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJDkBjmtM5LvFcQ8KlQmXONINz0eeldDk',
    appId: '1:612736301895:ios:6b3b1bfa77af7250ac2a62',
    messagingSenderId: '612736301895',
    projectId: 'habitseeding-prod',
    storageBucket: 'habitseeding-prod.firebasestorage.app',
    iosClientId: '612736301895-0qoorq8r0i3o6f8j0i42dsdqdb1eq14k.apps.googleusercontent.com',
    iosBundleId: 'com.habitseeding.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJDkBjmtM5LvFcQ8KlQmXONINz0eeldDk',
    appId: '1:612736301895:ios:6b3b1bfa77af7250ac2a62',
    messagingSenderId: '612736301895',
    projectId: 'habitseeding-prod',
    storageBucket: 'habitseeding-prod.firebasestorage.app',
    iosClientId: '612736301895-0qoorq8r0i3o6f8j0i42dsdqdb1eq14k.apps.googleusercontent.com',
    iosBundleId: 'com.habitseeding.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxMb8VRtABCQZr5cHKzPPs6EFFhCmG8I0',
    appId: '1:612736301895:web:70986d26c495c49dac2a62',
    messagingSenderId: '612736301895',
    projectId: 'habitseeding-prod',
    authDomain: 'habitseeding-prod.firebaseapp.com',
    storageBucket: 'habitseeding-prod.firebasestorage.app',
    measurementId: 'G-R3DWZM8RLX',
  );

}