// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCXvAbvOhPLjje6DfrO43-jiupGwh-Lao',
    appId: '1:250088132481:web:58453f7c98fa1ee54c2280',
    messagingSenderId: '250088132481',
    projectId: 'seerohabitseeding',
    authDomain: 'seerohabitseeding.firebaseapp.com',
    storageBucket: 'seerohabitseeding.firebasestorage.app',
    measurementId: 'G-3Q89HQYGQV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpHppCqhj2Webv5pfjPuY4xNQuK60NCnk',
    appId: '1:250088132481:android:a9c2393ae28d63054c2280',
    messagingSenderId: '250088132481',
    projectId: 'seerohabitseeding',
    storageBucket: 'seerohabitseeding.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANlBjsbvbaNiu8fu8bWOZdpx8IvICGzwU',
    appId: '1:250088132481:ios:20581c71c14b242f4c2280',
    messagingSenderId: '250088132481',
    projectId: 'seerohabitseeding',
    storageBucket: 'seerohabitseeding.firebasestorage.app',
    androidClientId: '250088132481-6e6a0a3o9aqdcb5v3vqf475mn4k08e35.apps.googleusercontent.com',
    iosClientId: '250088132481-euubh7rh8nrpp6led5tg26cbuhe11pq2.apps.googleusercontent.com',
    iosBundleId: 'com.habitseeding.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANlBjsbvbaNiu8fu8bWOZdpx8IvICGzwU',
    appId: '1:250088132481:ios:20581c71c14b242f4c2280',
    messagingSenderId: '250088132481',
    projectId: 'seerohabitseeding',
    storageBucket: 'seerohabitseeding.firebasestorage.app',
    androidClientId: '250088132481-6e6a0a3o9aqdcb5v3vqf475mn4k08e35.apps.googleusercontent.com',
    iosClientId: '250088132481-euubh7rh8nrpp6led5tg26cbuhe11pq2.apps.googleusercontent.com',
    iosBundleId: 'com.habitseeding.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCXvAbvOhPLjje6DfrO43-jiupGwh-Lao',
    appId: '1:250088132481:web:ce9f0462b6086f7b4c2280',
    messagingSenderId: '250088132481',
    projectId: 'seerohabitseeding',
    authDomain: 'seerohabitseeding.firebaseapp.com',
    storageBucket: 'seerohabitseeding.firebasestorage.app',
    measurementId: 'G-XF2PE5WNZ1',
  );

}